global:
  namespace: demo-sit
  replicaCount: 1
  imagePullSecrets: []
  # dev, sit, uat, staging, prod
  # This is used to set the environment for the application.
  env: sit

ingress:
  hosts:
    - host: chart-demo-sit.local
